### PR TITLE
Update readme and CT env variables, small clean improvements

### PR DESCRIPTION
**Pull request by devzom**
## Checklist
* [x] Unit tests
* [x] E2E tests
* [x] Documentation

### CODE REVIEW

**Comment by harm-meijer** [comment]
Replaced with [this](https://github.com/commercetools/sunrise-spa/pull/280) pull request

**Comment by devzom** [comment]
I think it's also update the dependencies and some minor issues in code

**Comment by harm-meijer** [comment]
> I think it's also update the dependencies and some minor issues in code

Can you link to what you need to update? I have updated a lot of code in development so it would cause conflicts, you can try to make the pull request to the development branch and see that many of the updates are no longer needed.

**Comment by devzom** [comment]
@harm-meijer thought that master is up-to-date, I'll then go and use **development** branch for actual project. Thank You, I'll compare the changes. : )

**Pull request closed without merging**
